name: CI/CD Pipeline for Node.js App

on:
  push:
    branches:
      - master
    paths-ignore:
      - helm/**
      - README.md

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Specify your Node.js version

      # Cache Node.js modules
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install dependencies
      - name: Install dependencies
        run: |
         npm ci
      # Run tests
      # - name: Run tests
      #   run: npm test
      #   env:
      #     CI: true

  build-and-push-docker:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/node-backend:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/node-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-to-kubernetes:
    needs: build-and-push-docker
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      # Configure kubeconfig for Kubernetes cluster
      # - name: Configure kubeconfig
      #   run: |
      #     mkdir -p $HOME/.kube
      #     echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
      #     chmod 600 $HOME/.kube/config

      # Update Kubernetes manifests with new image tag
      - name: Update image in Kubernetes manifests
        run: |
          sed -i 's|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/node-backend:${{ github.sha }}|' deployment.yml

      # Apply Kubernetes manifests
      # - name: Deploy to Kubernetes
      #   run: |
      #     kubectl apply -f k8s/deployment.yml
      #     kubectl apply -f k8s/service.yaml
      #   env:
      #     KUBECONFIG: $HOME/.kube/config

      - name: Azure Login
        # uses: azure/login@v2
        run: |
             az login --service-principal -u 27ede1c6-6852-4b1b-b8da-5a83d7b434d6 -p ${{secrets.SECRET_VALUE}} --tenant 30fe8ff1-adc6-444d-ba94-1238894df42c

        # with:
        #   creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS Credentials
        run: |
                 mkdir .kube/
                 touch .kube/config
                 az aks get-credentials --resource-group kml_rg_main-25beacfa3e5047fe --name kodekloud-demo
          
        # uses: azure/aks-set-context@v4
        # with:
        #   resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
        #   cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Deploy to AKS 
        run: |
                 kubectl apply -f deployment.yml
                 kubectl apply -f service.yml
                 kubectl apply -f ingress.yml
        # uses: azure/k8s-deploy@v5
        # with:
        #   namespace: default
        #   manifests: |
        #     deployment.yml
        #     service.yml
        #     ingress.yml
        #   images: |
        #     ${{ secrets.DOCKER_USERNAME }}/node-backend:${{ github.sha }}
        #   strategy: apply

      # Verify deployment
      # - name: Verify deployment
      #   run: |
      #     kubectl rollout status deployment/nodejs-deployment -n default --timeout=300s